### ISSUE TITLE
分享下以前的硬件历史固件

### ISSUE THREAD

**Issue by maxtony** [wgzeyu/GTX-Auto-Replace-Internet-Protocol-Address#2]
尤其是2代单卡008B和最新3代的固件，为老用户负责起见，请提供下载
由于3代固件不完善，能公开源码让有能力的人继续修正那最好不过了

**Comment by lmz1980** [comment]
您好，我的3代GTX硬件需要激活，还请您帮帮忙，万分感激。735772945

**Comment by ugvf2009** [comment]
有卖第3代机器无故障的，请给我发邮件。谢谢。 husini8@outlook.com

**Comment by maxtony** [comment]
不需要固件了，卖掉了，哈哈
这3.0的三张卡呼叫速度卡还远远不如其他家的一张卡，还留着干嘛，有视频有真相
http://v.youku.com/v_show/id_XMTY1NDI4MzQ5Ng==.html

**Comment by wgzeyu** [comment]
你开心就好




------------------ 原始邮件 ------------------
发件人: "maxtony";<notifications@github.com>;
发送时间: 2016年8月1日(星期一) 凌晨2:48
收件人: "wgzeyu/GTX-Auto-Replace-Internet-Protocol-Address"<GTX-Auto-Replace-Internet-Protocol-Address@noreply.github.com>; 

主题: Re: [wgzeyu/GTX-Auto-Replace-Internet-Protocol-Address] 分享下以前的硬件历史固件 (#2)




不需要固件了，卖掉了，哈哈
 这3.0的三张卡呼叫速度卡还远远不如其他家的一张卡，还留着干嘛，有视频有真相
 http://v.youku.com/v_show/id_XMTY1NDI4MzQ5Ng==.html
